eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostName: localhost  

microservice:
  ms1:
    endpoints:
      endpoint:
        uri: http://MICROSERVICE1/ms1/greeting
  ms2:
    endpoints:
      endpoint:
        uri: http://MICROSERVICE2/ms2/greeting   
